require 'cucumber'
require 'rspec'
require 'rake'
require 'selenium-webdriver'
require 'capybara'
require 'capybara/cucumber'
require 'capybara/rspec'
require 'pry'
require 'site_prism'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'
require 'capybara-screenshot/rspec'

